In [3]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Tensors

In [7]:
print(torch.__version__)

2.8.0


In [164]:
# A scalar is a single number (no dimensions).
scalar = torch.tensor(7)
scalar

tensor(7)

In [9]:
scalar.ndim  # number of dimensions

0

In [11]:
scalar.item()

7

In [12]:
vector = torch.tensor([7, 7])
vector.ndim  # number of dimensions

1

In [14]:
vector.shape  # shape of the vector

torch.Size([2])

In [15]:
vector.ndim  # number of dimensions

1

In [16]:
#Matrix
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
matrix.ndim  # number of dimensions

2

In [18]:
matrix.shape  # shape of the matrix

torch.Size([3, 3])

In [19]:
#Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],
                        [[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]],])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
tensor.ndim  # number of dimensions

3

In [21]:
tensor.shape

torch.Size([2, 3, 3])

In [23]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [25]:
# Randome Tensors
random_tensor = torch.rand(3, 3, 4)
random_tensor

tensor([[[0.9609, 0.3709, 0.4584, 0.7435],
         [0.8934, 0.6548, 0.8635, 0.1224],
         [0.9367, 0.8508, 0.7958, 0.0870]],

        [[0.6940, 0.3879, 0.9247, 0.3677],
         [0.9657, 0.3420, 0.7716, 0.3148],
         [0.1926, 0.4160, 0.3766, 0.8636]],

        [[0.5969, 0.4631, 0.0990, 0.0014],
         [0.4121, 0.5280, 0.6470, 0.6489],
         [0.1006, 0.3705, 0.3017, 0.8324]]])

In [28]:
random_image_size = torch.rand(size = (224, 224, 3))  # height, width, color channels (RGB)
random_image_size.shape, random_image_size.ndim

(torch.Size([224, 224, 3]), 3)

In [29]:
#Zeros and Ones
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32

In [38]:
torch.arange(start=5, end=100, step=10)  # 0 to 9

tensor([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [43]:
zero_to_ten = torch.arange(0,10,2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [44]:
ten_zero = torch.zeros_like(zero_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0])

**Note :** Tensor datatypes is one of the 3 big error you'll into with Pytorch & deep learning
1. Tensors not right datatype ( `tensor.dtype` )
2. Tensors not right shape  ( `tensor.shape` )
3. Tensors not on the right device  ( `tensor.device` )

In [47]:
float_32_tensor = torch.tensor([1.0, 2.0, 3.0], 
                               dtype=torch.float32 , # specify the data type of the tensor (float32,float16,int8 etc.,)
                               device="cpu", #What device the tensor should be put on (cpu, gpu)
                               requires_grad=False) # whether to track gradients for this tensor operations
float_32_tensor.dtype

torch.float32

In [50]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [53]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [55]:
tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
tensor * 10

tensor([10., 20., 30.])

In [56]:
torch.mul(tensor, 10)

tensor([10., 20., 30.])

In [57]:
torch.add(tensor, 10)

tensor([11., 12., 13.])

## Matrix multiplication
two main of perfoming multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix mutliplication (dot product)

there are two main rule performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(3, 2) @ (2, 3)` will work
* `(2, 3) @ (3, 2)` will work
2. The resulting matrix has the shape of the **outer 
* `(3, 2) @ (2, 3)` --> `(3, 3)`
* `(2, 3) @ (3, 2)` --> `(2, 2)`

In [ ]:
#Element-wise multiplication
print(tensor, '*', tensor)
print(torch.mul(tensor, tensor))

tensor([1., 2., 3.]) * tensor([1., 2., 3.])
tensor([1., 4., 9.])


In [60]:
#Matrix multiplication
tensor.matmul(tensor)

tensor(14.)

In [64]:
torch.matmul(torch.rand(2,3), torch.rand(3,2))

tensor([[0.5020, 0.4334],
        [0.6222, 0.8408]])

In [65]:
torch.matmul(torch.rand(3,2), torch.rand(2,3))

tensor([[0.5935, 1.0484, 0.3260],
        [0.8278, 1.1150, 0.3318],
        [0.2422, 0.3680, 0.1119]])

In [68]:
torch.matmul(torch.rand(2,3), torch.rand(3,4))

tensor([[0.2561, 0.6983, 0.4562, 0.1778],
        [0.8593, 1.4681, 1.3875, 0.6321]])

In [70]:
torch.matmul(torch.rand(4,3), torch.rand(3,2))

tensor([[0.3847, 0.4254],
        [0.6581, 0.8860],
        [0.6550, 1.2102],
        [0.7358, 1.1573]])

In [71]:
torch.matmul(torch.rand(2,3), torch.rand(3,4))

tensor([[0.4381, 0.2827, 0.1423, 0.4837],
        [0.5903, 0.3047, 0.6124, 0.7642]])

In [73]:
mat_a = torch.tensor([[1, 2],
                      [3, 4],
                      [5, 6]])
mat_b = torch.tensor([[1, 2],
                      [3, 4],
                      [5, 6]])
torch.matmul(mat_a, mat_b.T)  # Transpose

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [84]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [85]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [86]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [89]:
torch.mean(x.float()), x.float().mean()

(tensor(45.), tensor(45.))

In [90]:
torch.std(x.float()), x.float().std()

(tensor(30.2765), tensor(30.2765))

In [91]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [92]:
torch.median(x.float()), x.float().median()

(tensor(40.), tensor(40.))

In [ ]:
#find the position of minimum value
x.argmin()

tensor(0)

In [ ]:
#find the position of maximum value
x.argmax()

tensor(9)

In [95]:
x = torch.arange(1, 10)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
x_reshape = x.reshape(3,3)
x_reshape

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [99]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
z = x.view(1,9)
z, x

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [ ]:
z[:,0] = 5
z, x
#changing z changes x because view() share the same memory as the original tensor

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [106]:
x_stacked = torch.stack([x,x,x,x,x], dim=1)
x_stacked

tensor([[5, 5, 5, 5, 5],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9]])

In [119]:
# torch.squeeze() - removes all single. dimensiones from a tensor
z, z.shape

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [118]:
z.squeeze(), z.squeeze().shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [126]:
z_squeeze = z.squeeze()
z_squeeze, z_squeeze.shape

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [125]:
z_squeeze.unsqueeze(dim=0), z_squeeze.unsqueeze(dim=0).shape  # add a dimension at dim=0

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [140]:
data_original = torch.randn(224, 224, 3) # height, width, color channels (RGB)

data_permuted = data_original.permute(2, 0, 1)  # channel, height, width (change positions : 0->2, 1->0, 2->1 )
data_permuted.shape

torch.Size([3, 224, 224])

In [141]:
data_original[0,0,0], data_permuted[0,0,0]
print(data_original[0,0,0], data_permuted[0,0,0])

#if change the original tensor the permuted tensor will also (just change the positions)

data_original[0,0,0] = 10
print(data_original[0,0,0], data_permuted[0,0,0])

tensor(2.3845) tensor(2.3845)
tensor(10.) tensor(10.)


In [159]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [146]:
x[:,:,1]

tensor([[2, 5, 8]])

In [148]:
x[0,0,:], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [152]:
array = np.arange(1.0,10.0)
tensor_from_array = torch.from_numpy(array)
array, tensor_from_array

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [155]:
#remider, when creating a tensor from a numpy array the data types will be float64, but when creating a tensor using torch.arange the default data type is float32
array.dtype , torch.arange(1.0, 10.0).dtype

(dtype('float64'), torch.float32)

In [ ]:
random_tensor_a = torch.rand(3, 3, 4)
random_tensor_b = torch.rand(3, 3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[[0.2878, 0.0843, 0.2812, 0.9529],
         [0.3183, 0.4796, 0.6498, 0.8321],
         [0.4534, 0.2198, 0.2281, 0.9077]],

        [[0.1269, 0.8354, 0.0945, 0.9800],
         [0.8789, 0.6191, 0.2170, 0.0771],
         [0.8294, 0.7605, 0.3782, 0.7233]],

        [[0.4188, 0.0369, 0.7984, 0.7529],
         [0.2850, 0.8035, 0.7329, 0.4240],
         [0.0083, 0.2465, 0.5802, 0.3756]]])
tensor([[[0.3554, 0.9520, 0.3344, 0.6058],
         [0.9725, 0.1913, 0.3883, 0.4049],
         [0.0374, 0.0939, 0.7417, 0.0994]],

        [[0.2375, 0.5987, 0.8309, 0.3098],
         [0.1670, 0.7712, 0.2575, 0.0935],
         [0.9293, 0.4252, 0.7634, 0.4596]],

        [[0.8561, 0.4347, 0.6736, 0.9731],
         [0.7850, 0.7027, 0.0621, 0.7078],
         [0.6311, 0.5714, 0.6838, 0.1370]]])
tensor([[[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]],

        [[False, False, False, False],
         [False, False, False, False],
         [False, 

In [157]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 3, 4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]],

        [[0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090]]])
tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]],

        [[0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090]]])
tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

